<!-- RSD Lucky Wheel Wrapper -->
<div id="rwl-wheel-wrapper" class="rwl-wheel-wrapper" data-items="<?php echo esc_attr( $items_json ); ?>">

    <!-- Toast Notification Container -->
    <div id="rwl-toast-container" class="rwl-toast-container"></div>
    
    <!-- OTP/Login Section -->
    <div id="rwl-step-login" class="rwl-step-container active">
        <h3>گردونه شانس</h3>
        <p>شماره موبایل خود را وارد کنید تا شانس خود را امتحان کنید.</p>
        <div class="rwl-input-group">
            <input type="tel" id="rwl-mobile-input" placeholder="09xxxxxxxxx" maxlength="11">
            <button id="rwl-send-otp-btn" class="rwl-btn">ارسال کد تایید</button>
        </div>
        <div id="rwl-otp-section" style="display:none; margin-top:15px;">
            <p>کد تایید پیامک شده را وارد کنید:</p>
            <div class="rwl-input-group">
                <input type="text" id="rwl-otp-input" placeholder="کد ۵ رقمی" maxlength="5">
                <button id="rwl-verify-btn" class="rwl-btn rwl-btn-primary">تایید و شروع</button>
            </div>
            <p id="rwl-timer"></p>
        </div>
        <div class="rwl-message"></div>
    </div>

    <!-- Wheel Section -->
    <div id="rwl-step-wheel" class="rwl-step-container" style="display:none;">
        <div class="rwl-wheel-container">
            <div class="rwl-arrow"></div>
            <div class="rwl-wheel" id="rwl-wheel-element">
                <!-- Slices will be generated by JS -->
            </div>
        </div>
        <button id="rwl-spin-btn" class="rwl-spin-btn">چرخش</button>
    </div>

</div>

<!-- Result Popup -->
<div id="rwl-result-popup" class="rwl-popup-overlay" style="display:none;">
    <div class="rwl-popup-content">
        <span class="rwl-close-popup">&times;</span>
        <h3>تبریک!</h3>
        <p>شما برنده شدید:</p>
        <h2 id="rwl-won-item-title"></h2>
        <div class="rwl-code-box">
            <span id="rwl-won-code"></span>
            <button id="rwl-copy-btn" class="rwl-btn-small">کپی</button>
        </div>
    </div>
</div>

<!-- Floating Bar (Hidden by default) -->
<div id="rwl-floating-bar" class="rwl-floating-bar" style="display:none;">
    <div class="rwl-bar-content">
        <span>کد تخفیف شما: <strong id="rwl-bar-code"></strong></span>
        <span id="rwl-bar-timer"></span>
        <button id="rwl-bar-copy" class="rwl-btn-small">کپی</button>
    </div>
    <span class="rwl-close-bar">&times;</span>
</div>
